### ISSUE TITLE
Version 0.1.0 - whats needed?

### ISSUE THREAD

**Issue by kumavis** [nicola/js-ipld-selector#8]
Whats do we need to publish the first version?
Seems useful enough as is, if even an experiment

**Comment by vmx** [comment]
That's really outdated. There's also https://github.com/vmx/js-ipld-selectors/ which also is outdated again. For IPLD Selectors please see https://github.com/ipld/specs/pull/116.

**Comment by autonome** [comment]
@vmx Any action required here? Should stay open or can close?

**Comment by rvagg** [comment]
closing for repo archival
